import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class ImagesService {

  constructor() { }

  images = new Array();
  preloadImg = [
    "./../assets/images/main-page/LogoMakowyDom.png",
    "./../assets/images/main-page/HomePageImage-min.jpg",
    "./../assets/images/main-page/dom2-min.jpg",
    "./../assets/images/faces/b1-min.jpg",
    "./../assets/images/faces/b2-min.jpg",
    "./../assets/images/faces/b3-min.jpg",
    "./../assets/images/faces/b4-min.jpg",
    "./../assets/images/faces/b5-min.jpg",
    "./../assets/images/faces/b6-min.jpg",
    "./../assets/images/faces/b7-min.jpg",
    "./../assets/images/faces/g1-min.jpg",
    "./../assets/images/faces/g2-min.jpg",
    "./../assets/images/faces/g3-min.jpg",
    "./../assets/images/faces/g4-min.jpg",
    "./../assets/images/faces/g5-min.jpg",
    "./../assets/images/faces/kora-min.jpg",
    "./../assets/images/icons/big/user.png",
    "./../assets/images/icons/big/bed.png",
    "./../assets/images/icons/big/kitchen.png",
    "./../assets/images/icons/big/shower.png",
    "./../assets/images/icons/big/balcony.png",
    "./../assets/images/icons/big/wifiNew.png",
    "./../assets/images/icons/big/phone-call.png",
    "./../assets/images/icons/big/comment.png",
    "./../assets/images/icons/big/whatsapp.png",
    "./../assets/images/icons/big/couch.png",
    "./../assets/images/apartament/salon-web-min.jpg",
    "./../assets/images/dlagosci/grill/grill2-min.jpg",
    "./../assets/images/apartament/kuchnianew-min.jpg",
    "./../assets/images/apartament/lazeinkanew-min.jpg",
    "./../assets/images/apartament/pokojnew-min.jpg",
    "./../assets/images/apartament/salonnew-min.jpg",
    "./../assets/images/apartament/tarasnew-min.jpg",
    "./../assets/images/dlagosci/main/gry-min.jpg",
    "./../assets/images/dlagosci/main/grzyby-min.jpg",
    "./../assets/images/dlagosci/main/grzyby2-min.jpg",
    "./../assets/images/dlagosci/main/salasz-min.jpg",
    "./../assets/images/dlagosci/main/salatka1-min.jpg",
    "./../assets/images/dlagosci/grill/jedzenie-min.jpg",
    "./../assets/images/dlagosci/grill/salatka1-min.JPG",
    "./../assets/images/dlagosci/grill/grill1-min.jpg",
    "./../assets/images/dlagosci/grill/ogien1-min.jpg",
    "./../assets/images/dlagosci/grill/ogien2-min.jpg",
    "./../assets/images/dlagosci/grzyby/g1-min.jpg",
    "./../assets/images/dlagosci/grzyby/g2-min.jpg",
    "./../assets/images/dlagosci/grzyby/g3-min.jpg",
    "./../assets/images/dlagosci/planszowki/5s-min.jpg",
    "./../assets/images/dlagosci/planszowki/doble-min.jpg",
    "./../assets/images/dlagosci/planszowki/euro-min.jpg",
    "./../assets/images/dlagosci/planszowki/karty-min.jpg",
    "./../assets/images/dlagosci/planszowki/lego-min.jpg",
    "./../assets/images/dlagosci/lasy/l1-min.jpg",
    "./../assets/images/dlagosci/lasy/l2-min.jpg",
    "./../assets/images/dlagosci/lasy/l3-min.jpg",
    "./../assets/images/dlagosci/lasy/l4-min.jpg",
    "./../assets/images/dlagosci/lasy/l5-min.jpg",
    "./../assets/images/dlagosci/lasy/l5-min.jpg",
    "./../assets/images/icons/big/car.png",
    "./../assets/images/Okolica/krakow-min.jpg",
    "./../assets/images/Okolica/limanowaski2-min.jpg",
    "./../assets/images/Okolica/wieliczka1-min.jpg",
    "./../assets/images/Okolica/zakopane-min.jpg",
    "./../assets/images/Okolica/nowysacz-min.jpg",
    "./../assets/images/Okolica/paproc2-min.jpg",
    "./../assets/images/Okolica/pasierbiec-min.jpg",
    "./../assets/images/Okolica/rabkoland1-min.jpg",
    "./../assets/images/Okolica/szaflary-min.jpg",
    "./../assets/images/galeria/1.jpg",
    "./../assets/images/galeria/2.jpg",
    "./../assets/images/galeria/3.jpg",
    "./../assets/images/galeria/4.jpg",
    "./../assets/images/galeria/5.jpg",
    "./../assets/images/galeria/6.jpg",
    "./../assets/images/galeria/7.jpg",
    "./../assets/images/galeria/8.jpg",
    "./../assets/images/galeria/9.jpg",
    "./../assets/images/galeria/10.jpg",
    "./../assets/images/galeria/11.jpg",
    "./../assets/images/galeria/12.jpg",
    "./../assets/images/galeria/13.jpg",
    "./../assets/images/galeria/14.jpg",
    "./../assets/images/galeria/15.jpg",
    "./../assets/images/galeria/16.jpg",
    "./../assets/images/galeria/17.jpg",
    "./../assets/images/galeria/18.jpg",
    "./../assets/images/galeria/19.jpg",
    "./../assets/images/galeria/20.jpg",
    "./../assets/images/galeria/21.jpg",
    "./../assets/images/galeria/22.jpg",
    "./../assets/images/galeria/23.jpg",
    "./../assets/images/galeria/24.jpg",
    "./../assets/images/galeria/25.jpg",
    "./../assets/images/galeria/26.jpg",
    "./../assets/images/galeria/27.jpg",
    "./../assets/images/galeria/28.jpg",
    "./../assets/images/galeria/29.jpg",
    "./../assets/images/galeria/30.jpg",
    "./../assets/images/galeria/31.jpg",
    "./../assets/images/galeria/32.JPG",
    "./../assets/images/galeria/33.jpg",
    "./../assets/images/galeria/34.jpg",
    "./../assets/images/galeria/35.jpg",
    "./../assets/images/icons/big/fire.png",
    "./../assets/images/icons/big/backgammon.png",
    "./../assets/images/icons/big/washing-machine.png"
  ]
  preload() {
    for (var i = 0; i < this.preloadImg.length; i++) {
      this.images[i] = new Image()
      this.images[i].src = this.preloadImg[i]
    }
  }

}
